import { BattleTopic, QuizCategoryId, QuizQuestion } from '../types';

export const QUIZ_CATEGORIES: { id: QuizCategoryId; name: string; icon: string; color: string }[] = [
  { id: 'culture', name: 'Culture Générale', icon: 'earth', color: '#06B6D4' },
  { id: 'informatique', name: 'Informatique', icon: 'laptop', color: '#7C3AED' },
  { id: 'react_native', name: 'React Native', icon: 'react', color: '#61DAFB' },
];

export const SOLO_QUESTIONS: Record<QuizCategoryId, Omit<QuizQuestion, 'id'>[]> = {
  culture: [
    {
      categoryId: 'culture',
      question: 'Capitale du Cameroun ?',
      options: ['Douala', 'Yaoundé', 'Bafoussam', 'Garoua'],
      correctIndex: 1,
    },
    {
      categoryId: 'culture',
      question: 'Quelle est la plus grande planète ?',
      options: ['Terre', 'Mars', 'Jupiter', 'Saturne'],
      correctIndex: 2,
    },
    {
      categoryId: 'culture',
      question: "Qui a découvert l'Amérique ?",
      options: ['Magellan', 'Vasco de Gama', 'Christophe Colomb', 'Marco Polo'],
      correctIndex: 2,
    },
    {
      categoryId: 'culture',
      question: 'Combien de continents existe-t-il ?',
      options: ['5', '6', '7', '8'],
      correctIndex: 2,
    },
    {
      categoryId: 'culture',
      question: 'Quel océan est le plus vaste ?',
      options: ['Atlantique', 'Indien', 'Pacifique', 'Arctique'],
      correctIndex: 2,
    },
  ],
  informatique: [
    {
      categoryId: 'informatique',
      question: 'Que signifie CPU ?',
      options: [
        'Central Processing Unit',
        'Computer Personal Unit',
        'Core Program Utility',
        'Central Power Unit',
      ],
      correctIndex: 0,
    },
    {
      categoryId: 'informatique',
      question: 'Que signifie RAM ?',
      options: [
        'Random Access Memory',
        'Read Access Module',
        'Rapid Application Memory',
        'Remote Access Memory',
      ],
      correctIndex: 0,
    },
    {
      categoryId: 'informatique',
      question: "Qu'est-ce qu'un système d'exploitation ?",
      options: [
        'Un logiciel antivirus',
        'Un programme qui gère le matériel et les applications',
        'Un navigateur web',
        'Un type de processeur',
      ],
      correctIndex: 1,
    },
    {
      categoryId: 'informatique',
      question: 'Que signifie HTTP ?',
      options: [
        'HyperText Transfer Protocol',
        'High Transfer Text Protocol',
        'Host Transfer Text Process',
        'Hyper Transfer Text Program',
      ],
      correctIndex: 0,
    },
    {
      categoryId: 'informatique',
      question: 'Quel langage est compilé en bytecode JVM ?',
      options: ['Python', 'Java', 'JavaScript', 'C'],
      correctIndex: 1,
    },
  ],
  react_native: [
    {
      categoryId: 'react_native',
      question: 'À quoi sert useEffect ?',
      options: [
        'Gérer le state local',
        'Exécuter des effets de bord après le rendu',
        'Créer des composants',
        'Naviguer entre écrans',
      ],
      correctIndex: 1,
    },
    {
      categoryId: 'react_native',
      question: 'Différence entre State et Props ?',
      options: [
        'State est mutable par le composant, Props sont en lecture seule',
        'Props sont mutables, State est fixe',
        'Aucune différence',
        'State est global uniquement',
      ],
      correctIndex: 0,
    },
    {
      categoryId: 'react_native',
      question: 'Rôle de React Navigation ?',
      options: [
        'Gérer la navigation entre écrans',
        'Stocker des données',
        'Compiler le code',
        'Gérer les animations uniquement',
      ],
      correctIndex: 0,
    },
    {
      categoryId: 'react_native',
      question: 'Quel hook permet de mémoriser une valeur calculée ?',
      options: ['useState', 'useMemo', 'useEffect', 'useRef'],
      correctIndex: 1,
    },
    {
      categoryId: 'react_native',
      question: 'Hermes est utilisé pour ?',
      options: [
        'Le moteur JavaScript optimisé sur mobile',
        'La base de données',
        'Les icônes',
        'Le Bluetooth',
      ],
      correctIndex: 0,
    },
  ],
  git_commands: [],
};

export const BATTLE_TOPICS: BattleTopic[] = [
  {
    id: 'git_cmds',
    title: 'Citer les commandes Git',
    categoryId: 'git_commands',
    hint: 'Une commande par tour',
    validAnswers: [
      'git clone',
      'git pull',
      'git push',
      'git commit',
      'git status',
      'git branch',
      'git checkout',
      'git merge',
      'git fetch',
      'git rebase',
      'git stash',
      'git log',
      'git diff',
      'git add',
      'git reset',
      'git remote',
      'git tag',
      'git init',
      'git cherry-pick',
      'git blame',
    ],
  },
  {
    id: 'rn_hooks',
    title: 'Citer les hooks React',
    categoryId: 'react_native',
    hint: 'Un hook par tour',
    validAnswers: [
      'usestate',
      'useeffect',
      'usecontext',
      'usereducer',
      'usecallback',
      'usememo',
      'useref',
      'uselayouteffect',
      'useimperativehandle',
      'usedebugvalue',
      'useid',
      'usesyncexternalstore',
      'useinsertioneffect',
      'usedeferredvalue',
      'usetransition',
    ],
  },
  {
    id: 'capitales',
    title: 'Citer des capitales africaines',
    categoryId: 'culture',
    hint: 'Une capitale par tour',
    validAnswers: [
      'yaoundé',
      'nairobi',
      'cairo',
      'le caire',
      'lagos',
      'abidjan',
      'dakar',
      'rabat',
      'tunis',
      'alger',
      'addis-abeba',
      'kinshasa',
      'luanda',
      'accra',
      'pretoria',
      'maputo',
      'bamako',
      'ouagadougou',
    ],
  },
];

export const ACHIEVEMENTS_DEF = [
  { id: 'first_win', title: 'Première victoire', description: 'Gagner une partie', icon: 'trophy' },
  { id: 'solo_master', title: 'Solo Master', description: '10 parties solo', icon: 'star' },
  { id: 'battle_king', title: 'Roi du Battle', description: '5 victoires en Battle', icon: 'sword-cross' },
  { id: 'royale_legend', title: 'Légende Royale', description: 'Gagner un Battle Royale', icon: 'crown' },
  { id: 'streak_5', title: 'En série', description: '5 bonnes réponses consécutives', icon: 'fire' },
];
